#!/bin/perl
# $Id: tut.pl,v 1.3 2017/12/29 20:01:47 gbrandt Exp gbrandt $
#
#
#
#
#
#
#         # ###        ##### ##                                       ##
#       /  /###  /  ######  /##                                        ##
#      /  /  ###/  /#   /  / ##                                        ##       #
#     /  ##   ##  /    /  /  ##                                        ##      ##
#    /  ###           /  /   /                                         ##      ##
#   ##   ##          ## ##  /   ###  /###     /###   ###  /###     ### ##    ########
#   ##   ##   ###    ## ## /     ###/ #### / / ###  / ###/ #### / ######### ########
#   ##   ##  /###  / ## ##/       ##   ###/ /   ###/   ##   ###/ ##   ####     ##
#   ##   ## /  ###/  ## ## ###    ##       ##    ##    ##    ##  ##    ##      ##
#   ##   ##/    ##   ## ##   ###  ##       ##    ##    ##    ##  ##    ##      ##
#    ##  ##     #    #  ##     ## ##       ##    ##    ##    ##  ##    ##      ##
#     ## #      /       /      ## ##       ##    ##    ##    ##  ##    ##      ##
#      ###     /    /##/     ###  ##       ##    /#    ##    ##  ##    /#      ##
#       ######/    /  ########    ###       ####/ ##   ###   ###  ####/        ##
#         ###     /     ####       ###       ###   ##   ###   ###  ###          ##
#                 #
#                  ##
#
#
#
##########################################################################
###############  S P A W A R   S H A R E D   S E R V I C E S  ############
##########################################################################
#
#          File:  tut.pl
#        Author:  gbrandt
#          Date:  Tuesday, February  5, 2013
#
##########################################################################
#
#	Description:
#	Tape Useage Tracking.
#
#
#
###############  S P A W A R   S H A R E D   S E R V I C E S  ############
##########################################################################
#
#	Invocation:
#
#
#
##########################################################################
#
#	Revisions:
#
#
#        $Log: tut.pl,v $
#        Revision 1.3  2017/12/29 20:01:47  gbrandt
#        Added script name to report.
#
#        Revision 1.2  2017/12/29 19:36:36  gbrandt
#        Add report date and time information.
#        Relocated the server name's presentation.
#
#        Revision 1.1  2017/12/29 14:54:25  gbrandt
#        Initial revision
#
#
#
##########################################################################
##########################################################################

#
#
###############  S P A W A R   S H A R E D   S E R V I C E S  ############
##########################################################################
#                            Environmentals                              #
##########################################################################
#
#

$DEBUG   = 0;
$QRYFILE = "/tmp/tut.qry_$$";

#
#
###############  S P A W A R   S H A R E D   S E R V I C E S  ############
##########################################################################
#                               Processing                               #
##########################################################################
#
#

use Sys::Hostname;
unshift( @INC, "/home/scriptid/scripts/local_lib_perl" );
$Server = hostname;
require introduction;
@tutmonth =
  qw( January February March April May Jun July Aug September October November December );
( $sec, $min, $hour, $mday, $mon, $year, $wday ) = localtime();
$Today = sprintf "%4d%s%02d", $year + 1900, $tutmonth[$mon], $mday;
introduction("Tape Useage Tracking");

printf "          Generated by $0\n";
printf "          +-----------------------------------------------+\n";
printf "          |             Server: %10s                |\n", $Server;
printf "          |        Report Date: %s %d, %d         |\n",
  $tutmonth[$mon], $mday, $year + 1900;
printf "          |        Report Time: %d:%02d:%02d                  |\n",
  $hour, $min, $sec;
printf "          +-----------------------------------------------+\n";

getpools();
printf "     Tapes used last week:\n";
foreach $Pool (@PoolName) {
    Last( $Pool, "Week" );
}

printf "\n\n";
printf "     Tapes used last month:\n";

foreach $Pool (@PoolName) {
    Last( $Pool, "Month" );
}
printf "\n\n";
printf "     Tapes used last year:\n";

foreach $Pool (@PoolName) {
    Last( $Pool, "Year" );
}
#
#
###############  S P A W A R   S H A R E D   S E R V I C E S  ############
##########################################################################
#                                Subroutines                             #
##########################################################################
#
#
sub getpools {

    if ($DEBUG) {
        printf "     Debug Line: %3d %s\n", __LINE__,
          "     Getting list of tape pools.\n";
    }
    #
    #     build nsradmin query.
    #
    open( QRY, ">$QRYFILE" ) || die "\n\n     Unable to open $QRYFILE $!!\n\n";
    printf QRY ". type: NSR pool;enabled:yes;pool type:Backup\n";
    printf QRY "show name\n";
    printf QRY "print\n";
    close(QRY);
    #
    #     run query.
    #
    $QRY_CMD = "/usr/sbin/nsradmin -i $QRYFILE|";
    open( QRY, $QRY_CMD ) || die "\n\n     Unable to run $QRY_CMD $!!\n\n";
    $PoolCount = 0;
    while (<QRY>) {
        chomp();
        if (/^Current/)    # Skip query information.
        {
            next;
        }
        if (/^$/)          #Skip blank lines.
        {
            next;
        }
        tr/;//d;
        if (/name/) {
            ( $Property, $PoolName[$PoolCount] ) = split(/:/);
            $PoolCount++;
        }
    }

}    # end  of getpools

sub Last {
    $POOL   = shift;
    $Period = shift;
    printf "      %22s  ", $POOL;
    $cmd_last_week =
"mminfo -q \"pool=$POOL\" -t \"last $Period\" -r \"volume,%used,written,capacity\" 2>/dev/null|";
    $LWVount = 0;
    open( TapeCount, $cmd_last_week )
      || die "Can't run $cmd_last_week:   $!!\n";
    while (<TapeCount>) {
        if (/volume/) {
            next;
        }
        if (/$POOL/) {
            next;
        }

        #  print;
        $LWVount++;
    }
    close(TapeCount);
    if ($DEBUG) {
        printf "     Debug Line: %3d Tape Count: %2d\n", __LINE__, $LWVount;
    }
    printf "%3d\n", $LWVount;
}    #     End of Last
#
#
###############  S P A W A R   S H A R E D   S E R V I C E S  ############
##########################################################################
#                               House Keeping                            #
##########################################################################
#
#
